name: Kiem Tra Va Dong Goi Code

on:
  push:
    branches: [ "main" ]

jobs:
  kiem-tra-code:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Lay code ve may ao
        uses: actions/checkout@v4

      - name: 2. Cai dat Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. Chay Test
        # Bước này sẽ chạy file CalculatorTest.java của bạn
        run: mvn test

      # Bước 4: Đóng gói code thành file .jar (Chỉ làm khi bước Test ở trên đã Pass)
      - name: 4. Dong goi ung dung (Build JAR)
        run: mvn clean package -DskipTests

      # Bước 5: Deploy (Lưu file thành phẩm lên hệ thống GitHub)
      - name: 5. Deploy va Xuat xuong file
        uses: actions/upload-artifact@v4
        with:
          name: Ung-dung-May-tinh
          path: target/*.jar